
server:
  port: 8089
  
logging:
  level:
    org.springframework: INFO
    
spring:
  messages:
    basename: messages
  main:
    allow-bean-definition-overriding: true
    
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  security:
    user:
      name: username
      password: passw0rd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb